- name: Cleanup files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/root/.ssh/authorized_keys"
    - "/var/lib/yum/uuid"
    - "/var/log/nethserver-install.log"
    - "/var/log/shorewall-init.log"
    - "/var/log/firewall.log"
    - "/var/log/shorewall-init.log"
    - "/var/log/yum.log"
    - "/etc/pki/tls/certs/NSRV.crt"
    - "/etc/pki/tls/private/NSRV.key"
    - "/etc/ssh/ssh_host_*"
