---
- name: Wait for network up
  pause:
    seconds: 20

- name: Install cloud-init and utils
  yum:
    name:
      - cloud-init
      - cloud-utils-growpart
    state: present

- name: Copy cloud-init-config
  copy:
    src: files/99_pve_nethserver.cfg
    dest: /etc/cloud/cloud.cfg.d/

- name: Cleanup cloud-init
  command: "/usr/bin/cloud-init clean --seed --logs"
